import type { Metadata } from "next";
import { Open_Sans, Luckiest_Guy } from "next/font/google";
import "./globals.css";

const inter = Open_Sans({subsets:["latin"]});
const merienda = Luckiest_Guy({
  subsets: ["latin"], variable: "--Merienda",
  weight: "400"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className +" " +merienda.variable}>{children}</body>
    </html>
  );
}
